server:
  port: 8088


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.201:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  security:
    user:
      name: yuntian
      password: 944610721

  redis:
    host: 192.168.64.201
    port: 6379
    timeout: 10000ms
    database: 0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1ms
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0


# Logger Config
logging:
  level:
    com.yuntian.mybatisplus: debug